spring.application.name=loja3d
spring.datasource.url=jdbc:postgresql://localhost:5432/loja3d
spring.datasource.username=loja_user
spring.datasource.password=123456


spring.jps.hibernate.ddl-auto-update